repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      stages: [commit]
# -   repo: local
#     hooks:
#       - id: test
#         name: test
#         entry: make tests
#         language: system
#         pass_filenames: false
#         stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
-   repo: local
    hooks:
      - id: clean
        name: clean
        entry: make clean
        language: system
        pass_filenames: false
        stages: [commit]
